/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddLog: typeof import('./src/components/AddLog.vue')['default']
    HelloWorld: typeof import('./src/views/LoginView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfoModification: typeof import('./src/components/UserInfoModification.vue')['default']
  }
}
