/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddLog: typeof import('./src/components/AddLog.vue')['default']
    ChatList: typeof import('./src/components/ChatList.vue')['default']
    DeviceManagement: typeof import('./src/components/DeviceManagement.vue')['default']
    GuestLogManagement: typeof import('./src/components/GuestLogManagement.vue')['default']
    HelloWorld: typeof import('./src/views/LoginView.vue')['default']
    LogManagement: typeof import('./src/components/LogManagement.vue')['default']
    NearByHamer: typeof import('./src/components/NearByHamer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfoModification: typeof import('./src/components/UserInfoModification.vue')['default']
  }
}
